export const plants = {
    1: 'TDI',
    2: 'Gases',
    3: 'MTD',
    4: 'DNT',
    5: 'Densac',
    6: 'Cloro Soda',
    7: 'Evaporación',
    8: 'UHDENORA',
    9: 'Síntesis',
    10: 'Powell',
    11: 'PAC',
    12: 'Servicios',
    13: 'Playa tanques Norte',
    14: 'Playa tanques Sur',
    15: 'Playa tanques HCL',
    16: 'Expedición',
    17: 'Laboratorio',
    18: 'SMA',
    19: 'Taller Instrumentos',
    20: 'Taller Electrico',
    21: 'Taller Rotativos',
    22: 'Taller Estaticos'
}