export const TYPES = {
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    READ_ALL_EMPLOYEES: "READ_ALL_EMPLOYEES",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    NO_EMPLOYEE: "NO_EMPLOYEE",
};
